sequenceDiagram
    actor Player
    participant GamePlay as GamePlay<br/><<service>>
    participant Game
    participant Workspace
    participant HexTile

    Player ->> GamePlay: start()
    GamePlay ->> Game: start()
    Game ->> Workspace: createForPlayer()<br/>currentTile = StartingHexTile
    Workspace -->> Game: workspace
    GamePlay ->> Broadcaster: gameUpdate()

    Note over Player,Game: (time passes)

    Player ->> GamePlay: discard(card)
    GamePlay ->> Game: discard(card)
    Note over Game: (other stuff happens, too)
    Game ->> Workspace: discard()
    Workspace ->> HexTile: discard()
    HexTile -->> Workspace: next HexTile<br/>(based on state)
    GamePlay ->> Broadcaster: gameUpdate()

    Note over Player,Game: (time passes)<br/>Player clicks on PREDICT card for menu

    Player ->> GamePlay: actionsFor(PREDICT)
    GamePlay ->> Game: actionsFor(PREDICT)
    Game ->> Workspace: actionsFor(PREDICT)
    Workspace ->> HexTile: actionsFor(PREDICT)
    HexTile -->> Workspace: [Discard]
    Workspace -->> Game: [Discard]
    Game -->> GamePlay: [Discard]
    GamePlay -->> Player: [Discard]

    Player ->> GamePlay: actionsFor(WRITE_CODE)
    Note over Player,GamePlay: stuff happens
    GamePlay -->> Player: [Discard, Play]


    Player ->> GamePlay: play(WRITE_CODE)
    GamePlay ->> Game: play(WRITE_CODE)
    Game ->> Workspace: play(WRITE_CODE)
    Workspace ->> HexTile: play(WRITE_CODE)<br/>throws exception if not allowed

